FROM python:3.10-bullseye

WORKDIR /api

ADD ./requirements.txt ./

RUN --mount=type=cache,target=/root/.cache/pip/ \
    pip install -r requirements.txt

CMD ["gunicorn","-b","0.0.0.0:8080","tweedle.wsgi:application"]