# Generated by Django 4.0.1 on 2022-05-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='likes',
            field=models.BooleanField(default=False),
        ),
    ]
